name: Terraform

on:
  workflow_dispatch: # <-- allows manual trigger

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: terraform init

    - name: Create terraform.auto.tfvars
      run: |
        echo 'vpc_cidr_block = "${{ secrets.VPC_CIDR_BLOCK }}"' > terraform.auto.tfvars
        echo 'private_subnet_cidr_blocks = ${{ secrets.PRIVATE_SUBNET_CIDR_BLOCKS }}' >> terraform.auto.tfvars
        echo 'public_subnet_cidr_blocks = ${{ secrets.PUBLIC_SUBNET_CIDR_BLOCKS }}' >> terraform.auto.tfvars

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.event_name == 'workflow_dispatch'
      run: terraform apply -auto-approve
